name: update-tags

on:
  schedule:
    - cron:  '41 * * * *'

jobs:
  update-tags:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: "${{ secrets.DOCKER_HUB_USERNAME }}"
      DOCKER_HUB_PASSWORD: "${{ secrets.DOCKER_HUB_PASSWORD }}"
    steps:
    - uses: actions/checkout@v2
    - name: Update tags.yml and README.md
      run: ./update.sh
    - name: Commit
      run: |
        if [ -n "$(git status -s)" ]; then
          git config --local user.email "webmaster+orchicd@orchitech.cz"
          git config --local user.name "Orchi CD Bot"
          git add tags.yml README.md
          git commit -m "Update tags"
          git push
        fi
